language: python
services:
  - postgresql
  - mysql
python:
  - "3.6"
env:
- DB=sqlite
- DB=postgres
- DB=mysql

before_script:
  - pip install --upgrade pytest pytest-cov codecov
  - |
    set -e
    if [ "${DB}" == "postgres" ]; then
      psql -c 'create database hydra_base_test;' -U postgres
    fi
    if [ "${DB}" == "mysql" ]; then
      mysql -e 'CREATE DATABASE hydra_base_test;'
    fi

install:
  - pip install -e .

script:
  - pytest tests --db-backend=${DB} --cov-report term --cov hydra_base

after_success:
  - codecov

