"""simplify network

Revision ID: 1eb51c6159ac
Revises: 7d6099524c02
Create Date: 2017-12-29 11:36:35.323359

"""
from alembic import op
import sqlalchemy as sa
from hydra_base import db

# revision identifiers, used by Alembic.
revision = '1eb51c6159ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('tNetwork', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('name', sa.String(length=200), nullable=False, server_default=sa.text("''")))
        batch_op.add_column(sa.Column('description', sa.String(length=1000), nullable=True))
        batch_op.drop_constraint(u'unique net name', type_='unique')

    with op.batch_alter_table('tNetwork', schema=None) as batch_op:
        op.execute("update tNetwork set id = network_id ")
        op.execute("update tNetwork set name = network_name")
        op.execute("update tNetwork set description = network_description")

        batch_op.create_unique_constraint('unique net name', ['name', 'project_id'])

        batch_op.drop_column('network_id')
        batch_op.drop_column('network_name')
        batch_op.drop_column('network_description')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tScenario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'tNetwork', ['network_id'], ['network_id'])
        batch_op.create_index('ix_tScenario_scenario_id', ['scenario_id'], unique=False)
        batch_op.create_index('ix_tScenario_network_id', ['network_id'], unique=False)
        batch_op.drop_index(batch_op.f('ix_tScenario_scenario_id'))
        batch_op.drop_index(batch_op.f('ix_tScenario_network_id'))

    with op.batch_alter_table('tRule', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'tNetwork', ['network_id'], ['network_id'])
        batch_op.create_index('ix_tRule_ref_key', ['ref_key'], unique=False)
        batch_op.create_index('ix_tRule_node_id', ['node_id'], unique=False)
        batch_op.create_index('ix_tRule_network_id', ['network_id'], unique=False)
        batch_op.create_index('ix_tRule_link_id', ['link_id'], unique=False)
        batch_op.create_index('ix_tRule_group_id', ['group_id'], unique=False)
        batch_op.drop_index(batch_op.f('ix_tRule_ref_key'))
        batch_op.drop_index(batch_op.f('ix_tRule_node_id'))
        batch_op.drop_index(batch_op.f('ix_tRule_network_id'))
        batch_op.drop_index(batch_op.f('ix_tRule_link_id'))
        batch_op.drop_index(batch_op.f('ix_tRule_group_id'))

    with op.batch_alter_table('tResourceType', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'tNetwork', ['network_id'], ['network_id'])

    with op.batch_alter_table('tResourceScenario', schema=None) as batch_op:
        batch_op.create_index('ix_tResourceScenario_scenario_id', ['scenario_id'], unique=False)
        batch_op.create_index('ix_tResourceScenario_resource_attr_id', ['resource_attr_id'], unique=False)
        batch_op.drop_index(batch_op.f('ix_tResourceScenario_scenario_id'))
        batch_op.drop_index(batch_op.f('ix_tResourceScenario_resource_attr_id'))

    with op.batch_alter_table('tResourceGroupItem', schema=None) as batch_op:
        batch_op.create_index('ix_tResourceGroupItem_scenario_id', ['scenario_id'], unique=False)
        batch_op.drop_index(batch_op.f('ix_tResourceGroupItem_scenario_id'))

    with op.batch_alter_table('tResourceGroup', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'tNetwork', ['network_id'], ['network_id'])

    with op.batch_alter_table('tResourceAttrMap', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'tNetwork', ['network_a_id'], ['network_id'])
        batch_op.create_foreign_key(None, 'tNetwork', ['network_b_id'], ['network_id'])

    with op.batch_alter_table('tResourceAttr', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'tNetwork', ['network_id'], ['network_id'])
        batch_op.create_index('ix_tResourceAttr_ref_key', ['ref_key'], unique=False)
        batch_op.create_index('ix_tResourceAttr_project_id', ['project_id'], unique=False)
        batch_op.create_index('ix_tResourceAttr_node_id', ['node_id'], unique=False)
        batch_op.create_index('ix_tResourceAttr_network_id', ['network_id'], unique=False)
        batch_op.create_index('ix_tResourceAttr_link_id', ['link_id'], unique=False)
        batch_op.create_index('ix_tResourceAttr_group_id', ['group_id'], unique=False)
        batch_op.drop_index(batch_op.f('ix_tResourceAttr_ref_key'))
        batch_op.drop_index(batch_op.f('ix_tResourceAttr_project_id'))
        batch_op.drop_index(batch_op.f('ix_tResourceAttr_node_id'))
        batch_op.drop_index(batch_op.f('ix_tResourceAttr_network_id'))
        batch_op.drop_index(batch_op.f('ix_tResourceAttr_link_id'))
        batch_op.drop_index(batch_op.f('ix_tResourceAttr_group_id'))

    with op.batch_alter_table('tNote', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'tNetwork', ['network_id'], ['network_id'])
        batch_op.create_index('ix_tNote_scenario_id', ['scenario_id'], unique=False)
        batch_op.create_index('ix_tNote_ref_key', ['ref_key'], unique=False)
        batch_op.create_index('ix_tNote_project_id', ['project_id'], unique=False)
        batch_op.create_index('ix_tNote_node_id', ['node_id'], unique=False)
        batch_op.create_index('ix_tNote_network_id', ['network_id'], unique=False)
        batch_op.create_index('ix_tNote_link_id', ['link_id'], unique=False)
        batch_op.create_index('ix_tNote_group_id', ['group_id'], unique=False)
        batch_op.drop_index(batch_op.f('ix_tNote_scenario_id'))
        batch_op.drop_index(batch_op.f('ix_tNote_ref_key'))
        batch_op.drop_index(batch_op.f('ix_tNote_project_id'))
        batch_op.drop_index(batch_op.f('ix_tNote_node_id'))
        batch_op.drop_index(batch_op.f('ix_tNote_network_id'))
        batch_op.drop_index(batch_op.f('ix_tNote_link_id'))
        batch_op.drop_index(batch_op.f('ix_tNote_group_id'))

    with op.batch_alter_table('tNode', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'tNetwork', ['network_id'], ['network_id'])

    with op.batch_alter_table('tNetworkOwner', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'tNetwork', ['network_id'], ['network_id'])

    with op.batch_alter_table('tNetwork', schema=None) as batch_op:
        batch_op.add_column(sa.Column('network_description', sa.VARCHAR(length=1000), nullable=True))
        batch_op.add_column(sa.Column('network_name', sa.VARCHAR(length=60), nullable=False))
        batch_op.add_column(sa.Column('network_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('unique net name', type_='unique')
        batch_op.create_unique_constraint(u'unique net name', ['network_name', 'project_id'])
        batch_op.drop_column('name')
        batch_op.drop_column('id')
        batch_op.drop_column('description')

    with op.batch_alter_table('tMetadata', schema=None) as batch_op:
        batch_op.create_index('ix_tMetadata_dataset_id', ['dataset_id'], unique=False)
        batch_op.drop_index(batch_op.f('ix_tMetadata_dataset_id'))

    with op.batch_alter_table('tLink', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'tNetwork', ['network_id'], ['network_id'])

    with op.batch_alter_table('tDataset', schema=None) as batch_op:
        batch_op.create_index('ix_tDataset_dataset_id', ['dataset_id'], unique=False)
        batch_op.drop_index(batch_op.f('ix_tDataset_dataset_id'))

    # ### end Alembic commands ###
