#!/bin/bash
# Installs the image manager as a local command
BASEDIR=$PWD
source "$BASEDIR/env.sh"

mkdir -p ${BASEDIR}/current

sed "s|<REPO_FOLDER>|${BASEDIR}|" ${BASEDIR}/templates/repo-images-manager.sh > ${BASEDIR}/current/repo-images-manager.sh
sed -i -e "s|<NOTES>|This is an autogenerated file. Don't modify it! Go to templates folder and then run command-installer.sh|" ${BASEDIR}/current/repo-images-manager.sh
chmod a+x ${BASEDIR}/current/repo-images-manager.sh

command_name="${SPECIFIC_IMAGE_NAME}-repo-images-manager"
rm ~/bin/${command_name}
ln -s ${BASEDIR}/current/repo-images-manager.sh ~/bin/${command_name}


sed "s|<REPO_FOLDER>|${BASEDIR}|" ${BASEDIR}/templates/login-to-remote-repository.sh > ${BASEDIR}/current/login-to-remote-repository.sh
chmod a+x ${BASEDIR}/current/login-to-remote-repository.sh

command_name="${SPECIFIC_IMAGE_NAME}-login-to-remote-repository"
rm ~/bin/${command_name}
ln -s ${BASEDIR}/current/login-to-remote-repository.sh ~/bin/${command_name}
