name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-20.04
    env:
      TEST_DB: hydra_base_test
      COV_MIN: 70  # Minimum acceptable coverage level
      TEST_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TEST_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      HYDRA_CONFIGSET: default_configset.json
      HYDRA_DB_SERVER: 127.0.0.1
      HYDRA_DB_NAME: hydradb
      HYDRA_DB_USER: root
      HYDRA_DB_PASSWD: root
      HYDRA_DB_AUTOCREATE: Y
      HYDRA_MYSQL_POOL_PREPING: True
      HYDRA_MYSQL_POOL_SIZE: 10
      HYDRA_MYSQL_POOL_RECYCLE: 300
      HYDRA_MYSQL_POOL_TIMEOUT: 10
      HYDRA_MYSQL_MAX_OVERFLOW: 20
      HYDRA_CACHETYPE: memcached
      HYDRA_CACHEHOST: 127.0.0.1
      HYDRA_LOG_CONFPATH: hydra-base/logging.conf
      HYDRA_LOG_FILEDIR: .hydra/log
      HYDRA_MONGO_HOST: localhost
      HYDRA_MONGO_PORT: 27017
      HYDRA_MONGO_DB_NAME: hydra
      HYDRA_MONGO_USER:
      HYDRA_MONGO_PASSWD:
      HYDRA_MONGO_DATASETS: datasets
      HYDRA_MONGO_THRESHOLD: 4096
      HYDRA_MONGO_DIRECT_LOCATION_TOKEN: mongo_direct
      HYDRA_MONGO_VALUE_LOCATION_KEY: value_storage_location
      HYDRA_DISABLE_HDF: False
      HYDRA_HDF_FILESTORE: /tmp

    strategy:
      matrix:
        py_version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.py_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py_version }}

      - name: Install dependencies
        run: |
             pip install --upgrade wheel
             pip install --upgrade pytest
             pip install --upgrade pytest-cov  # Includes coverage
             pip install --upgrade pytest-order  # Run test_login last

      - name: Setup MySQL
        run: |
             sudo systemctl start mysql
             mysql -e "create database $TEST_DB;" -uroot -proot
             mysql -e "show databases;" -uroot -proot

      - name: Setup MongoDB
        run: sudo systemctl start mongod

      - name: Setup Memcache
        run: |
             sudo apt-get install -y memcached=1.5.22-2
             sudo systemctl start memcached

      - name: Install hydra-base
        run: |
             pip install -r requirements.txt
             pip install git+https://github.com/hydraplatform/hydra-client-python.git
             pip install git+https://github.com/hydraplatform/hydra-server.git
             pip install -e .

      - name: Run pytests
        run: pytest --db-backend=mysql --cov=hydra_base
