name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      TEST_DB: hydra_base_test
      COV_MIN: 65  # Minimum acceptable coverage level

    strategy:
      matrix:
        py_version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.py_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py_version }}

      - name: Install dependencies
        run: |
             pip install --upgrade wheel
             pip install --upgrade pytest
             pip install --upgrade pytest-cov  # Includes coverage
             pip install --upgrade pytest-order  # Run test_login last

      - name: Setup MySQL
        run: |
             sudo systemctl start mysql
             mysql -e "create database $TEST_DB;" -uroot -proot
             mysql -e "show databases;" -uroot -proot

      - name: Setup Memcache
        run: |
             sudo apt-get install -y memcached
             sudo apt-get install -y libmemcached-dev
             sudo systemctl start memcached

      - name: Install hydra-base
        run: |
             pip install git+https://github.com/hydraplatform/hydra-client-python.git
             pip install git+https://github.com/hydraplatform/hydra-server.git
             pip install -e .

      - name: Run pytests
        run: pytest --db-backend=mysql --cov=hydra_base --cov-fail-under=$COV_MIN
