name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-20.04
    env:
      TEST_DB: hydra_base_test
      COV_MIN: 70  # Minimum acceptable coverage level
      TEST_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TEST_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      HYDRA_DB_SERVER: 127.0.0.1
      HYDRA_DB_NAME: hydra_base_test
      HYDRA_DB_USER: root
      HYDRA_DB_PASSWD: root
      HYDRA_DB_AUTOCREATE: Y
      HYDRA_DB_PREPING: True
      HYDRA_CACHETYPE: memcached
      HYDRA_LOG_CONFPATH: hydra-base/logging.conf
      HYDRA_LOG_FILEDIR: .hydra/log

    strategy:
      matrix:
        py_version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.py_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py_version }}

      - name: Install dependencies
        run: |
             pip install --upgrade wheel
             pip install --upgrade pytest
             pip install --upgrade pytest-cov  # Includes coverage
             pip install --upgrade pytest-order  # Run test_login last

      - name: Setup MySQL
        run: |
             sudo systemctl start mysql
             mysql -e "create database $TEST_DB;" -uroot -proot
             mysql -e "show databases;" -uroot -proot

      - name: Setup MongoDB
        run: sudo systemctl start mongod

      - name: Setup Memcache
        run: |
             sudo apt-get install -y memcached=1.5.22-2
             sudo systemctl start memcached

      - name: Install hydra-base
        run: |
             pip install -r requirements.txt
             pip install git+https://github.com/hydraplatform/hydra-client-python.git
             pip install git+https://github.com/hydraplatform/hydra-server.git
             pip install -e .

      - name: Run pytests
        run: pytest --db-backend=mysql --cov=hydra_base
